# Site settings
title: Tariq Hawis
email: tariqhawis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here where I share my Ideas, researches, projects and contributions to Cybersecurity space and open source community
  Subscribe and keep updated with my last posts
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://www.tariqhawis.com # the base hostname & protocol for your site
twitter_username: tariqhawis
github_username:  tariqhawis
image: https://www.tariqhawis.com/img/avatar.png
remote_theme: chrisrhymes/bulma-clean-theme
google_analytics: UA-10799151-3
livereload: true
favicon: /favicon.ico

# Pagination settings
paginate: 5
paginate_path: "/howto/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: thawes

# Build settings
markdown: kramdown

#Syntax Highlighter
highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - github-pages
  - jekyll-feed

sass:
  style: compressed

collections:
  projects: 
    output: true
    layout: project
    show_sidebar: false
  writeups:
    output: true
    layout: post
    show_sidebar: false
  stories:
    output: true

exclude: [node_modules, gulpfile.js, vendor, package.json]

footer_menu: footer_menu

defaults:
  -
    scope:
      path: ""
    values:
      hero_darken: true
      author: "Tariq Hawis"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      hero_image: /img/stories-hero.jpg
      show_sidebar: false
      middle_text: true
  -
    scope:
      path: ""
      type: "stories"
    values:
      author: "Tariq Hawis"
      layout: post
      hero_image: /img/stories-hero.jpg

# SEO
author:
  twitter: TariqHawis
lang: en
logo: /img/avatar.png
twitter:
  username: TariqHawis
  card: summary_large_image
facebook:
  publisher: https://www.facebook.com/Tariq-Hawis-102907161281331/
social:
  name: Tariq Hawis
  links:
    - https://www.twitter.com/tariqhawis
    - https://www.facebook.com/Tariq-Hawis-102907161281331/
    - https://github.com/tariqhawis
