# Site settings
title: Tariq Hawis
email: prof.tariq@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal website where I share my research findings, developed tools, and tutorial videos
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://www.tariqhawis.com # the base hostname & protocol for your site
twitter_username: tariqhawis
github_username:  tariqhawis
image: /img/landing-hero1.jpg


remote_theme: chrisrhymes/bulma-clean-theme
#theme: bulma-clean-theme
google_analytics: UA-10799151-3
#livereload: true
#favicon: /favicon.ico

# Pagination settings
paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: thawes

# Build settings
markdown: kramdown

#Syntax Highlighter
highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - github-pages
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

sass:
  style: compressed

collections:
  stories:
    output: true
  products:
    output: true
    layout: product
    show_sidebar: false

#exclude: [node_modules, gulpfile.js, vendor]

footer_menu: footer_menu

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Tariq Hawis"
      layout: post
      hero_image: /img/blog-hero.jpg
      show_sidebar: true

# SEO
author:
  twitter: TariqHawis
lang: en_US
twitter:
  username: TariqHawis
  card: summary_large_image
#facebook:
#  publisher: https://www.facebook.com/
social:
  name: Tariq Hawis
  links:
    - https://www.twitter.com/tariqhawis
    #- https://www.facebook.com/
    - https://github.com/tariqhawis

#feed:
#  collections:
#    - stories
